default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39933_development

test:
  <<: *default
  database: furima_39933_test

production:
  <<: *default
  database: furima_39933_production
  username: furima_39933
  password: <%= ENV["FURIMA_39933_DATABASE_PASSWORD"] %>
